title: Zhenning Wang's Homepage
page-top-title: Zhenning Wang's Homepage
top-section-bg-text: Exploring Physics through Experiments
home-subtitle: Zhenning Wang
copyright-text: '&copy; Zhenning Wang 2025-2026. All Rights Reserved.'
